services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: eventos_api_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - eventos_api_network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: eventos_api_nginx
    restart: unless-stopped
    ports:
      - "8180:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - eventos_api_network
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: eventos_api_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: eventos_api
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3106:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - eventos_api_network

  redis:
    image: redis:7.2-alpine
    container_name: eventos_api_redis
    restart: unless-stopped
    ports:
      - "6179:6379"
    volumes:
      - redis_data:/data
    networks:
      - eventos_api_network
    command: redis-server --appendonly yes

networks:
  eventos_api_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
